apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-microservice
  labels:
    app: rag-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rag-microservice
  template:
    metadata:
      labels:
        app: rag-microservice
    spec:
      containers:
      - name: rag-microservice
        image: your-registry/rag-microservice:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URL
          value: "mongodb://mongodb-service:27017/ragdb"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10