apiVersion: v1
kind: Service
metadata:
  name: rag-microservice-service
spec:
  selector:
    app: rag-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access is needed